language: python
sudo: false

python:
 - "2.7"
#   - "3.4"
#   - "3.5"
#   - "3.6"

cache: pip

install:
   - pip install -r requirements.txt
   - sudo apt update
#     - sudo apt upgrade
   - sudo apt install -y python-pip
   - sudo apt install build-essential libssl-dev libffi-dev python-dev
   - pip install pytest
#     - pip install -r requirements.txt

script:
   - python ex1.py
   - python ex2.py
   - python ex3.py
   - python ex4.py
   - python ex5.py
   - python ex6.py
   - python ex7.py
   - python ex8.py
   - python ex9.py
   - python ex10.py
   - python ex11.py < ex11_inputs.txt
   - python ex12.py < ex12_inputs.txt
   - python ex13.py first second third
   - python ex14.py zed < ex14_inputs.txt
   - python ex15.py ex15_sample.txt < ex15_inputs.txt
   - python ex16.py  test.txt < enter.sh
   - python ex17.py  test.txt new_file < enter.sh
   - python ex18.py
   - python ex19.py
   - python ex20.py test.txt
   - python ex21.py
   - python ex24.py
   - python < ex25_inputs.sh
