language: python
sudo: false

python:
 - "2.7"
#   - "3.4"
#   - "3.5"
#   - "3.6"

cache: pip

install:
   - pip install -r requirements.txt
   - sudo apt update
#     - sudo apt upgrade
   - sudo apt install -y python-pip
   - sudo apt install build-essential libssl-dev libffi-dev python-dev
   - pip install pytest
#     - pip install -r requirements.txt

script:
   - python exercises/ex1.py
   - python exercises/ex2.py
   - python exercises/ex3.py
   - python exercises/ex4.py
   - python exercises/ex5.py
   - python exercises/ex6.py
   - python exercises/ex7.py
   - python exercises/ex8.py
   - python exercises/ex9.py
   - python exercises/ex10.py
<<<<<<< HEAD
   - python ex11.py < ex11_inputs.txt
   - python ex12.py < ex12_inputs.txt
   - python ex13.py first second third
   - python ex14.py zed < ex14_inputs.txt
   - python ex15.py ex15_sample.txt < ex15_inputs.txt
   - python ex16.py  test.txt < enter.sh
   - python ex17.py  test.txt new_file < enter.sh
   - python ex18.py
   - python ex19.py
   - python ex20.py test.txt
   - python ex21.py
   - python ex24.py
=======
   - python exercises/ex11.py < answers/ex11_inputs.txt
   - python exercises/ex12.py < answers/ex12_inputs.txt
   - python exercises/ex13.py first second third
   - python exercises/ex14.py zed <  answers/ex14_inputs.txt
   - python exercises/ex15.py ex15_sample.txt < answers/ex15_inputs.txt
   - python exercises/ex16.py  test.txt < bash/enter.sh
   - python exercises/ex17.py  test.txt new_file < bash/enter.sh
   - python exercises/ex18.py
   - python exercises/ex19.py
   - python exercises/ex20.py test.txt
   - python exercises/ex21.py
   - python exercises/ex24.py
>>>>>>> b57e2b0f22d5df9da2c5eabb6ce2f34786fb487e
   - python < ex25_inputs.sh
